### ISSUE TITLE
Generate Drivers for Validation of Individual Modules with Bash Script

### ISSUE THREAD

**Issue by dwood2265** [RuleML/issues-ruleml#75]
Implement accepted option of - 
http://wiki.ruleml.org/index.php/Generate_Drivers_for_Validation_of_Individual_Modules_with_Bash_Script#Option_1

**Comment by greenTara** [comment]
Resolved with https://github.com/RuleML/deliberation-ruleml/commit/d099ccc2e6b09b5e2c8ec370cd73eb07e10ffea4
